"""AI Reports — generate a role-aware report for any scope and export it."""

import os
import sys

# Make the modules in src/ importable (pages live one level below the root).
sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "src"))

import streamlit as st

import analytics
import llm_service
import ui

st.set_page_config(page_title="AI Reports", page_icon="📝", layout="wide")
ui.require_db()
ui.llm_badge()

st.title("📝 AI Executive Reports")
st.caption("Generate a role-aware report for a module, a project, or the whole org. "
           "Falls back to a data-driven summary if no model is running.")

scope = st.radio("Scope", ["Org-wide", "Project", "Module"], horizontal=True)
role = st.selectbox("Audience / tone", ["Unit Head", "Project Manager", "Team Lead"])

target_label = "organisation"
if scope == "Project":
    projects = {f"{p['name']} · {p['unit']}": p for p in analytics.list_projects()}
    proj = projects[st.selectbox("Project", list(projects.keys()))]
elif scope == "Module":
    modules = {f"{m['name']} · {m['project']}": m for m in analytics.list_modules()}
    mod = modules[st.selectbox("Module", list(modules.keys()))]

if st.button("Generate Report", type="primary"):
    with st.spinner("Generating…"):
        if scope == "Org-wide":
            result = llm_service.generate_org_report(role)
            target_label = "organisation"
        elif scope == "Project":
            result = llm_service.generate_project_report(proj["id"], role)
            target_label = proj["name"]
        else:
            result = llm_service.generate_module_report(mod["id"], role)
            target_label = mod["name"]
    st.session_state["report_result"] = result
    st.session_state["report_name"] = f"{target_label}_{role}".replace(" ", "_")

result = st.session_state.get("report_result")
if result:
    st.divider()
    st.markdown(result["text"])
    if result["source"] == "llm":
        st.caption("✅ Generated by the configured model.")
    else:
        st.caption("⚠️ Model offline — data-driven fallback.")
    st.download_button(
        "⬇️ Download as Markdown",
        data=result["text"],
        file_name=f"report_{st.session_state.get('report_name', 'report')}.md",
        mime="text/markdown",
    )
