"""Shared UI helpers for the Streamlit pages: risk colours, cached loaders, AI widget."""

import os

import streamlit as st

import analytics
import config
import llm_service

RISK_COLORS = {"low": "#2ecc71", "medium": "#f39c12", "high": "#e74c3c"}
RISK_EMOJI = {"low": "🟢", "medium": "🟠", "high": "🔴"}


def require_db() -> None:
    """Stop the page with a helpful message if the DB hasn't been generated."""
    if not os.path.exists(config.DB_PATH):
        st.warning(
            "No database found. Generate it first:\n\n"
            "```\npython src/generate_data.py\n```"
        )
        st.stop()


# --- Cached analytics loaders (cleared when the DB file changes) ----------
def _db_mtime() -> float:
    try:
        return os.path.getmtime(config.DB_PATH)
    except OSError:
        return 0.0


@st.cache_data
def rankings(weeks: int = 4, _mtime: float = 0.0) -> list[dict]:
    return analytics.get_all_module_rankings(weeks)


@st.cache_data
def org_summary(weeks: int = 4, _mtime: float = 0.0) -> dict:
    return analytics.get_org_summary(weeks)


def load_rankings(weeks: int = 4) -> list[dict]:
    return rankings(weeks, _db_mtime())


def load_org_summary(weeks: int = 4) -> dict:
    return org_summary(weeks, _db_mtime())


def style_risk_level(df, column: str = "risk_level"):
    """Return a pandas Styler that colours the risk-level column."""
    def _color(val):
        bg = RISK_COLORS.get(val, "#888")
        return f"background-color: {bg}; color: white; font-weight: 600;"

    return df.style.map(_color, subset=[column])


# --- AI insight widget + LLM status badge --------------------------------
@st.cache_data(ttl=30)
def _llm_available_cached() -> bool:
    return llm_service.is_available()


def llm_badge() -> None:
    """Small sidebar caption showing whether the LLM endpoint is reachable."""
    if _llm_available_cached():
        st.sidebar.caption(f"LLM: 🟢 connected · `{config.LLM_MODEL}`")
    else:
        st.sidebar.caption("LLM: ⚪ offline — using data-driven fallback")


def render_ai_insight(label: str, cache_key: str, generate_fn) -> None:
    """On-demand, cached AI narrative for the current view.

    Shows a button; on click runs generate_fn() (which returns
    {"text", "source"}) inside a spinner and caches it in session_state under
    cache_key, so it does not regenerate on every interaction.
    """
    st.markdown(f"#### 🧠 {label}")
    cached = st.session_state.get(cache_key)
    btn = "Regenerate AI insight" if cached else "Generate AI insight"
    if st.button(btn, key=f"btn_{cache_key}"):
        with st.spinner("Generating… (falls back to a data summary if no model is running)"):
            st.session_state[cache_key] = generate_fn()
        cached = st.session_state[cache_key]

    if cached:
        st.markdown(cached["text"])
        if cached["source"] == "llm":
            st.caption(f"✅ Generated by `{config.LLM_MODEL}`")
        else:
            st.caption("⚠️ Model offline — data-driven fallback. Start a model "
                       "(see README) and regenerate for AI prose.")
    else:
        st.caption("Click to generate an AI narrative for this view.")
